/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rr225300' at '9/23/16 10:34 AM' with Gradle 2.12
 *
 * @author rr225300, @date 9/23/16 10:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
